#pragma once

/*
    AUv3 Audio Unit Wrapper

    Copyright (c) 2024 Timo Kaluza (defiantnerd)

    This file is part of the clap-wrappers project which is released under MIT License.
    See file LICENSE or go to https://github.com/free-audio/clap-wrapper for full license details.

    ClapAUv3AudioUnit is the AUAudioUnit subclass that wraps a CLAP plugin as an AUv3 Audio Unit.
*/

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnullability-completeness"

#import <AudioToolbox/AudioToolbox.h>
#import <AVFoundation/AVFoundation.h>
#import <CoreAudioKit/CoreAudioKit.h>
#import <CoreMIDI/CoreMIDI.h>

#import "auv3_platform.h"

#pragma clang diagnostic pop

@class ClapAUv3AudioUnit;

// The view controller is also the AUAudioUnitFactory.
// Apple's AUv3 model requires the NSExtensionPrincipalClass to be the
// AUViewController subclass which also conforms to AUAudioUnitFactory.
@interface ClapAUv3ViewController : AUViewController <AUAudioUnitFactory>
@property(nonatomic, strong) ClapAUv3AudioUnit *audioUnit;
// Subclasses (generated by build-helper) override this to provide plugin-specific info
- (AUAudioUnit *)createAudioUnitWithComponentDescription:(AudioComponentDescription)desc
                                                   error:(NSError **)error;
@end

@interface ClapAUv3AudioUnit : AUAudioUnit
{
 @package
  // Weak back-reference to the factory VC that created this AU.
  // Set by [ClapAUv3ViewController setAudioUnit:] during factory creation.
  // Used by requestViewControllerWithCompletionHandler: so the host can
  // obtain the VC for displaying the plugin's custom UI.
  __weak ClapAUv3ViewController *_factoryViewController;
}

- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError **)outError
                                    clapName:(NSString *)clapName
                                      clapId:(NSString *)clapId
                                   clapIndex:(int)clapIndex;

// Called by the view controller to create the CLAP GUI and learn how big it
// wants to be. Deliberately separate from parenting: CLAP allows get_size()
// once gui->create() has run, before set_parent() (clap/ext/gui.h), and AUv3
// needs the size before the view has a window to parent into.
// Returns YES if the CLAP plugin has a GUI and it was successfully created.
// Idempotent — repeated calls just hand back the size.
- (BOOL)prepareGUIAndReturnWidth:(uint32_t *)outWidth height:(uint32_t *)outHeight;

// Called by the view controller once the view has a window: embeds the
// already-created CLAP GUI and shows it. Returns NO if the GUI wasn't prepared.
// parentView is an NSView on macOS and a UIView on iOS (see auv3_platform.h).
- (BOOL)parentGUIInView:(CLAPWRAP_ViewClass *)parentView;

// Called by the view controller when the view is being torn down.
- (void)destroyGUI;

// Called by the view controller to check if the CLAP GUI supports resizing.
- (BOOL)canResizeGUI;

// Called by the view controller when the host resizes the view.
- (BOOL)setGUISize:(uint32_t)width height:(uint32_t)height;

// Called by the view controller to establish the back-reference needed
// for gui_request_resize to set preferredContentSize on the VC.
- (void)setViewController:(ClapAUv3ViewController *)vc;

@end
